package edu.ahut.mapper;

import edu.ahut.entity.Cnwords;
import edu.ahut.entity.CnwordsExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CnwordsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cnwords
     *
     * @mbg.generated Tue May 08 13:14:25 CST 2018
     */
    long countByExample(CnwordsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cnwords
     *
     * @mbg.generated Tue May 08 13:14:25 CST 2018
     */
    int deleteByExample(CnwordsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cnwords
     *
     * @mbg.generated Tue May 08 13:14:25 CST 2018
     */
    int insert(Cnwords record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cnwords
     *
     * @mbg.generated Tue May 08 13:14:25 CST 2018
     */
    int insertSelective(Cnwords record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cnwords
     *
     * @mbg.generated Tue May 08 13:14:25 CST 2018
     */
    List<Cnwords> selectByExample(CnwordsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cnwords
     *
     * @mbg.generated Tue May 08 13:14:25 CST 2018
     */
    int updateByExampleSelective(@Param("record") Cnwords record, @Param("example") CnwordsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cnwords
     *
     * @mbg.generated Tue May 08 13:14:25 CST 2018
     */
    int updateByExample(@Param("record") Cnwords record, @Param("example") CnwordsExample example);

    List<Cnwords> translate(Cnwords cnwords);

    List<Cnwords> tips(Cnwords cnwords);
}