package edu.ahut.entity;

public class Cnwords {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cnwords.word
     *
     * @mbg.generated Tue May 08 13:14:25 CST 2018
     */
    private String word;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cnwords.explaintation
     *
     * @mbg.generated Tue May 08 13:14:25 CST 2018
     */
    private String explaintation;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cnwords.word
     *
     * @return the value of cnwords.word
     *
     * @mbg.generated Tue May 08 13:14:25 CST 2018
     */
    public String getWord() {
        return word;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cnwords.word
     *
     * @param word the value for cnwords.word
     *
     * @mbg.generated Tue May 08 13:14:25 CST 2018
     */
    public void setWord(String word) {
        this.word = word == null ? null : word.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cnwords.explaintation
     *
     * @return the value of cnwords.explaintation
     *
     * @mbg.generated Tue May 08 13:14:25 CST 2018
     */
    public String getExplaintation() {
        return explaintation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cnwords.explaintation
     *
     * @param explaintation the value for cnwords.explaintation
     *
     * @mbg.generated Tue May 08 13:14:25 CST 2018
     */
    public void setExplaintation(String explaintation) {
        this.explaintation = explaintation == null ? null : explaintation.trim();
    }
}