package edu.ahut.entity;

public class Enwords {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column enwords.ID
     *
     * @mbg.generated Thu May 03 18:00:22 CST 2018
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column enwords.word
     *
     * @mbg.generated Thu May 03 18:00:22 CST 2018
     */
    private String word;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column enwords.soundmark
     *
     * @mbg.generated Thu May 03 18:00:22 CST 2018
     */
    private String soundmark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column enwords. explaintation
     *
     * @mbg.generated Thu May 03 18:00:22 CST 2018
     */
    private String explaintation;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column enwords.ID
     *
     * @return the value of enwords.ID
     *
     * @mbg.generated Thu May 03 18:00:22 CST 2018
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column enwords.ID
     *
     * @param id the value for enwords.ID
     *
     * @mbg.generated Thu May 03 18:00:22 CST 2018
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column enwords.word
     *
     * @return the value of enwords.word
     *
     * @mbg.generated Thu May 03 18:00:22 CST 2018
     */
    public String getWord() {
        return word;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column enwords.word
     *
     * @param word the value for enwords.word
     *
     * @mbg.generated Thu May 03 18:00:22 CST 2018
     */
    public void setWord(String word) {
        this.word = word == null ? null : word.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column enwords.soundmark
     *
     * @return the value of enwords.soundmark
     *
     * @mbg.generated Thu May 03 18:00:22 CST 2018
     */
    public String getSoundmark() {
        return soundmark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column enwords.soundmark
     *
     * @param soundmark the value for enwords.soundmark
     *
     * @mbg.generated Thu May 03 18:00:22 CST 2018
     */
    public void setSoundmark(String soundmark) {
        this.soundmark = soundmark == null ? null : soundmark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column enwords. explaintation
     *
     * @return the value of enwords. explaintation
     *
     * @mbg.generated Thu May 03 18:00:22 CST 2018
     */
    public String getExplaintation() {
        return explaintation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column enwords. explaintation
     *
     * @param explaintation the value for enwords. explaintation
     *
     * @mbg.generated Thu May 03 18:00:22 CST 2018
     */
    public void setExplaintation(String explaintation) {
        this.explaintation = explaintation == null ? null : explaintation.trim();
    }
}